import { createSystem, Types } from "@iwsdk/core";
import { Signal } from "@preact/signals-core";
import { EffectParam } from "./AudioReactor.js";

/**
 * VisualDNA — the complete visual fingerprint of a song.
 * Generated by AudioAnalyzerSystem during the learning phase.
 * Consumed by TunnelGenerator, PsychedelicFX, and GeometryTouch systems.
 */
export interface VisualDNA {
  /** Estimated BPM (beats per minute) */
  bpm: number;
  /** How many beats have been detected in the learning window */
  beatCount: number;
  /** Spectral classification */
  spectralProfile: "bass" | "mid" | "treble" | "full";
  /** Ring density scalar: 0.2 (sparse) → 1.0 (dense) */
  baseRingDensity: number;
  /** Which tunnel shader to use (0=Aurora, 1=Scanline, 2=Starfield, 3=Plasma) */
  baseShaderIndex: number;
  /** Touch sensitivity multiplier: how much touch amplifies */
  touchSensitivity: number;
  /** Beat pulse strength scalar */
  beatMultiplier: number;
  /** Per-ring-type spawn weight [box, sphere, torus, octahedron] */
  ringShapeBias: [number, number, number, number];
  /** Dominant hue range [minHue, maxHue] */
  colorHueRange: [number, number];
  /** Ring movement pattern */
  patternMode: "uniform" | "wave" | "burst" | "cascade";
  /** Whether analysis is complete */
  locked: boolean;
}

/**
 * AudioAnalyzerSystem
 *
 * Builds a VisualDNA fingerprint during the first ~30s of audio playback.
 * After locking, the DNA is stable for the rest of the song.
 *
 * Analysis pipeline:
 *   1. BPM detection via autocorrelation of bass energy
 *   2. Spectral profile classification (bass/mid/treble/full)
 *   3. Dynamic range measurement (whisper-to-shout ratio)
 *   4. Rhythmic complexity (beat interval variance)
 *   5. Dominant hue from FFT peak frequency
 *
 * Output → VisualDNA signals consumed by other systems.
 */
export class AudioAnalyzerSystem extends createSystem({}, {}) {
  /** Finalized visual DNA — stable after learning phase */
  readonly visualDNA = new Signal<VisualDNA>({
    bpm: 120,
    beatCount: 0,
    spectralProfile: "full",
    baseRingDensity: 0.5,
    baseShaderIndex: 0,
    touchSensitivity: 1.0,
    beatMultiplier: 1.0,
    ringShapeBias: [0.25, 0.25, 0.25, 0.25],
    colorHueRange: [0, 360],
    patternMode: "uniform",
    locked: false,
  });

  // ── Learning window ────────────────────────────────────────────────
  private learningDurationMs = 30000;
  private learningStartMs = 0;
  private isLearning = false;
  private hasLocked = false;

  // ── Raw analysis buffers ───────────────────────────────────────────
  private bassHistory: number[] = [];
  private beatTimestamps: number[] = [];
  private spectralHistory: { bass: number; mid: number; treble: number }[] = [];
  private dynamicHistory: number[] = []; // RMS energy per frame
  private peakFrequencyHistory: number[] = []; // dominant frequency bin

  // ── Beat detection (mirrors AudioReactor's logic but tracks intervals) ──
  private bassHistorySize = 20;
  private beatThreshold = 0.08;
  private lastBeatTime = 0;
  private beatCooldownMs = 40;

  // ── FFT data (written by AudioReactorSystem each frame) ─────────────
  private _pendingBass = 0;
  private _pendingMid = 0;
  private _pendingTreble = 0;
  private _pendingEnergy = 0;
  private _pendingFreqData: Uint8Array = new Uint8Array(256);
  private _pendingIsPlaying = false;

  /** Called by AudioReactorSystem each frame with latest analysis data */
  ingestFrame(
    bass: number,
    mid: number,
    treble: number,
    energy: number,
    freqData: Uint8Array,
    isPlaying: boolean
  ): void {
    this._pendingBass = bass;
    this._pendingMid = mid;
    this._pendingTreble = treble;
    this._pendingEnergy = energy;
    this._pendingFreqData = freqData;
    this._pendingIsPlaying = isPlaying;
  }

  init() {}

  update(delta: number, _time: number): void {
    if (this.hasLocked) return;

    // Start learning on first frame of audio
    if (this._pendingIsPlaying && !this.isLearning) {
      this.isLearning = true;
      this.learningStartMs = performance.now();
      console.log("[AudioAnalyzer] Learning started");
    }

    if (!this.isLearning || !this._pendingIsPlaying) return;

    const elapsed = performance.now() - this.learningStartMs;

    // Collect data into rolling buffers
    this.bassHistory.push(this._pendingBass);
    if (this.bassHistory.length > this.bassHistorySize) this.bassHistory.shift();

    this.dynamicHistory.push(this._pendingEnergy);
    if (this.dynamicHistory.length > 300) this.dynamicHistory.shift();

    this.spectralHistory.push({
      bass: this._pendingBass,
      mid: this._pendingMid,
      treble: this._pendingTreble,
    });
    if (this.spectralHistory.length > 300) this.spectralHistory.shift();

    // Dominant frequency bin (most energetic bin in bass range)
    const freq = this._pendingFreqData;
    let peakBin = 0;
    let peakVal = 0;
    for (let i = 0; i < Math.floor(freq.length * 0.25); i++) {
      if (freq[i] > peakVal) {
        peakVal = freq[i];
        peakBin = i;
      }
    }
    this.peakFrequencyHistory.push(peakBin);
    if (this.peakFrequencyHistory.length > 300) this.peakFrequencyHistory.shift();

    // Beat detection — track timestamps for BPM calculation
    const bassAvg =
      this.bassHistory.length > 0
        ? this.bassHistory.reduce((a, v) => a + v, 0) / this.bassHistory.length
        : 0;
    const isBassHit = bassAvg > 0 && this._pendingBass > bassAvg * 1.15;
    const now = performance.now();
    if (isBassHit && now - this.lastBeatTime > this.beatCooldownMs) {
      this.beatTimestamps.push(now);
      this.lastBeatTime = now;
    }

    // Check if learning window complete
    if (elapsed >= this.learningDurationMs) {
      this.lockDNA();
    }
  }

  private lockDNA(): void {
    if (this.hasLocked) return;
    this.hasLocked = true;
    this.isLearning = false;

    const dna = this.deriveDNA();
    this.visualDNA.value = dna;
    console.log("[AudioAnalyzer] DNA locked:", JSON.stringify(dna, null, 2));
  }

  private deriveDNA(): VisualDNA {
    // ── BPM: autocorrelation of beat timestamps ─────────────────────
    let bpm = 120;
    let beatCount = this.beatTimestamps.length;

    if (this.beatTimestamps.length >= 4) {
      // Compute median beat interval
      const intervals: number[] = [];
      for (let i = 1; i < this.beatTimestamps.length; i++) {
        intervals.push(this.beatTimestamps[i] - this.beatTimestamps[i - 1]);
      }
      intervals.sort((a, b) => a - b);
      const medianInterval =
        intervals[Math.floor(intervals.length / 2)];
      if (medianInterval > 0) {
        bpm = Math.round(60000 / medianInterval);
        bpm = Math.max(60, Math.min(200, bpm)); // clamp to reasonable range
      }
    }

    // ── Spectral profile ───────────────────────────────────────────
    const avgSpec = this.averageSpectral();
    let spectralProfile: VisualDNA["spectralProfile"] = "full";
    const { bass, mid, treble } = avgSpec;

    if (bass > mid * 1.4 && bass > treble * 1.4) spectralProfile = "bass";
    else if (treble > bass * 1.4 && treble > mid * 1.4) spectralProfile = "treble";
    else if (mid > bass * 1.2 && mid > treble * 1.2) spectralProfile = "mid";
    else spectralProfile = "full";

    // ── Dynamic range ───────────────────────────────────────────────
    const avgDyn = this.dynamicHistory.reduce((a, v) => a + v, 0) / this.dynamicHistory.length;
    const maxDyn = Math.max(...this.dynamicHistory, 0.01);
    const minDyn = Math.min(...this.dynamicHistory);
    const dynamicRange = maxDyn / Math.max(minDyn, 0.001);

    // ── Ring density ────────────────────────────────────────────────
    // Dense songs → many rings (more going on sonically)
    // BPM affects spacing: faster songs = rings feel closer together
    const tempoFactor = bpm / 120; // normalize around 120bpm
    let baseRingDensity = Math.min(1.0, Math.max(0.2,
      avgDyn * 0.5 + tempoFactor * 0.3 + (spectralProfile === "full" ? 0.2 : 0)
    ));

    // ── Shader index ───────────────────────────────────────────────
    // Aurora: bass-dominant, gentle
    // Scanline: mid-dominant, rhythmic
    // Starfield: treble-heavy, sparse feel
    // Plasma: full-spectrum, high energy
    let baseShaderIndex = 0;
    switch (spectralProfile) {
      case "bass":   baseShaderIndex = 0; break; // Aurora
      case "mid":    baseShaderIndex = 1; break; // Scanline
      case "treble": baseShaderIndex = 2; break; // Starfield
      case "full":   baseShaderIndex = 3; break; // Plasma
    }

    // Override if high dynamic range → Plasma always wins for big swings
    if (dynamicRange > 2.5) baseShaderIndex = 3;

    // ── Touch sensitivity ──────────────────────────────────────────
    // Quiet/subtle songs need more touch amplification
    const touchSensitivity = avgDyn < 0.3 ? 2.0 : avgDyn < 0.6 ? 1.5 : 1.0;

    // ── Beat multiplier ─────────────────────────────────────────────
    // High BPM = tighter beat pulses, stronger multiplier
    const beatMultiplier = Math.max(0.5, Math.min(2.0, (bpm / 100)));

    // ── Ring shape bias ─────────────────────────────────────────────
    // Derived from rhythmic complexity (beat interval variance)
    const complexity = this.measureRhythmicComplexity();
    const [box, sphere, torus, octa] = this.shapeBiasFromComplexity(
      complexity,
      spectralProfile
    );

    // ── Color hue range from dominant frequency ────────────────────
    const avgPeakBin =
      this.peakFrequencyHistory.reduce((a, v) => a + v, 0) /
      Math.max(this.peakFrequencyHistory.length, 1);
    const dominantFreqHz = (avgPeakBin / (this._pendingFreqData.length * 0.25)) * 22050;
    const hue = this.frequencyToHue(dominantFreqHz);
    const hueRange: [number, number] = [(hue - 40 + 360) % 360, (hue + 40) % 360];

    // ── Pattern mode ────────────────────────────────────────────────
    // Determine from beat regularity
    const regularity = this.measureBeatRegularity();
    let patternMode: VisualDNA["patternMode"] = "uniform";
    if (regularity < 0.3) patternMode = "burst";
    else if (regularity < 0.6) patternMode = "wave";
    else if (beatCount > 40) patternMode = "cascade";

    // High BPM + high complexity → cascade
    if (bpm > 140 && complexity > 0.5) patternMode = "cascade";

    return {
      bpm,
      beatCount,
      spectralProfile,
      baseRingDensity,
      baseShaderIndex,
      touchSensitivity,
      beatMultiplier,
      ringShapeBias: [box, sphere, torus, octa],
      colorHueRange: hueRange,
      patternMode,
      locked: true,
    };
  }

  private averageSpectral(): { bass: number; mid: number; treble: number } {
    if (this.spectralHistory.length === 0) {
      return { bass: 0.5, mid: 0.5, treble: 0.5 };
    }
    let bass = 0, mid = 0, treble = 0;
    for (const s of this.spectralHistory) {
      bass += s.bass;
      mid += s.mid;
      treble += s.treble;
    }
    const n = this.spectralHistory.length;
    return { bass: bass / n, mid: mid / n, treble: treble / n };
  }

  private measureRhythmicComplexity(): number {
    if (this.beatTimestamps.length < 4) return 0.5;
    const intervals: number[] = [];
    for (let i = 1; i < this.beatTimestamps.length; i++) {
      intervals.push(this.beatTimestamps[i] - this.beatTimestamps[i - 1]);
    }
    const mean = intervals.reduce((a, v) => a + v, 0) / intervals.length;
    const variance =
      intervals.reduce((a, v) => a + Math.abs(v - mean), 0) / intervals.length;
    // Normalize: 0 = perfectly regular, 1 = completely irregular
    return Math.min(1.0, variance / Math.max(mean, 1));
  }

  private measureBeatRegularity(): number {
    if (this.beatTimestamps.length < 4) return 0.5;
    const intervals: number[] = [];
    for (let i = 1; i < this.beatTimestamps.length; i++) {
      intervals.push(this.beatTimestamps[i] - this.beatTimestamps[i - 1]);
    }
    const mean = intervals.reduce((a, v) => a + v, 0) / intervals.length;
    const variance =
      intervals.reduce((a, v) => a + (v - mean) ** 2, 0) / intervals.length;
    const stdDev = Math.sqrt(variance);
    // CV (coefficient of variation): lower = more regular
    return Math.min(1.0, stdDev / Math.max(mean, 1));
  }

  private shapeBiasFromComplexity(
    complexity: number,
    profile: VisualDNA["spectralProfile"]
  ): [number, number, number, number] {
    // Complexity 0: regular rhythm → geometric shapes (torus, box)
    // Complexity 1: irregular → organic shapes (octahedron, sphere)
    const organic = complexity;
    const geometric = 1 - complexity;

    // Bass-dominant → bold shapes (torus, box)
    // Treble-dominant → sharp shapes (octahedron)
    // Full-spectrum → balanced
    let box = 0.25, sphere = 0.25, torus = 0.25, octa = 0.25;

    if (profile === "bass") {
      torus = 0.45 * geometric + 0.1;
      box = 0.30 * geometric + 0.1;
      octa = 0.15 * organic + 0.1;
      sphere = 0.10 * organic + 0.1;
    } else if (profile === "treble") {
      octa = 0.45 * organic + 0.15;
      sphere = 0.30 * organic + 0.15;
      torus = 0.15 * geometric;
      box = 0.10 * geometric;
    } else if (profile === "mid") {
      box = 0.40 * geometric + 0.1;
      torus = 0.25 * geometric + 0.1;
      sphere = 0.20 * organic + 0.1;
      octa = 0.15 * organic + 0.1;
    } else {
      // full — balanced
      box = 0.25 + 0.05 * geometric;
      sphere = 0.25 + 0.05 * organic;
      torus = 0.25;
      octa = 0.25;
    }

    // Normalize
    const total = box + sphere + torus + octa;
    return [box / total, sphere / total, torus / total, octa / total];
  }

  private frequencyToHue(freqHz: number): number {
    // Map 20Hz–20kHz to hue 0–360 (log scale)
    const minLog = Math.log2(20);
    const maxLog = Math.log2(20000);
    const t = (Math.log2(Math.max(20, Math.min(20000, freqHz))) - minLog) / (maxLog - minLog);
    return t * 300; // 0–300° leaves room for wrap
  }
}